title: Peas Brie Rice
email: 
description: >-
  Collection of recipes to keep expanding my cooking skills and my coding skills!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yadrybug.github.io" 
twitter_username: 
github_username: YaDryBug

# Build settings
theme: minima
plugins:
  - jekyll-feed

name:               "RE:cipes"

# Navigation
nav:
  - name:           "About"
    remote:         false
    localpath:      "about"
  - name:           "Download"
    remote:         true
    href:           ""

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag